### ISSUE TITLE
Latest dind (20) doesn't work with docker 19 api

### ISSUE THREAD

**Issue by irotem** [gocd/docker-gocd-agent-dind#16]
I am recieving a **"failed to adjust OOM score for shim"** message when running in a docker 19 environment.

See issue:  https://github.com/containerd/containerd/issues/4837

Can you add an argument or tag that supports dind 19?

**Hotfix:** Changed to `FROM docker:19-dind`
You can test out with the following image: `rotembar/gocd-agent-dind-19:v21.1.0`

**Comment by maxbalan** [comment]
a workaround for anyone looking for a quick fix to their pipeline, just downgrade the agent version, seems to be working fine as there is no breaking changes in the api.

**Comment by csotiriou** [comment]
I am running this inside a small Kubernetes Cluster with k3s. Downgrading the agent did not work for me as it produced other errors in the Java code of the agent (I took a look inside the running agent pod). 

However, using `rotembar/gocd-agent-dind-19:v21.1.0` did the trick for me and I was able to proceed, thank you. 

As an FYI for k3s users, containerd claim to have fixed the issue in the linked issue above, but I am not sure if this fix was released in 1.4 (which k3s uses) or 1.5.

**Comment by chadlwilson** [comment]
I believe this should be fixed in containerd `1.4.4` as well as `1.5`, however I believe it is the version inside the Docker image that is of relevance rather than k3s, so probably needs an official GoCD image rebuild which currently only happens alongside releases. Which hasn't happened for a while :-(

Current official image version `gocd-agent-docker-dind:v21.2.0` has Docker `20.10.5` in it which includes containerd `1.4.3`. I believe it needs to be `>= 20.10.6` to have the fixed containerd version.

**Comment by chadlwilson** [comment]
Please let us know if there is still an issue on a later version of the image and we can re-open.
