### ISSUE TITLE
Error response from daemon: cgroups: cgroup mountpoint does not exist: unknown.

### ISSUE THREAD

**Issue by gregoryfischer** [gocd/docker-gocd-agent-dind#18]
Using `gocd/gocd-agent-docker-dind:v19.12.0` I am able to get the agent to auto register with my GoCD server but when I attempt to run a docker container (eg. docker run hello-world) inside the docker-gocd-agent-dind container I get this error.

Error response from daemon: cgroups: cgroup mountpoint does not exist: unknown.

This very error is discussed in many forums but the resolution to the issue is always the following which does not work as this image is a using a read only file system.

```
$ sudo mkdir /sys/fs/cgroup/systemd
$ sudo mount -t cgroup -o none,name=systemd cgroup /sys/fs/cgroup/systemd
```
So what are your suggestions for addressing this issue in the docker-gocd-agent-dind image?

docker info
```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea838
 Built:             Wed Nov 13 07:22:05 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea838
  Built:            Wed Nov 13 07:28:45 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
bash-5.0$ docker info
Client:
 Debug Mode: false

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 1
 Server Version: 19.03.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.76-linuxkit
 Operating System: Alpine Linux v3.10
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 1.939GiB
 Name: e39753f998de
 ID: 4LUZ:PFG2:ERW4:HKBG:FCXH:PMC5:7FE5:QNCZ:VJZJ:F3FT:VHBT:MDWT
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

WARNING: API is accessible on http://0.0.0.0:2375 without encryption.
         Access to the remote API is equivalent to root access on the host. Refer
         to the 'Docker daemon attack surface' section in the documentation for
         more information: https://docs.docker.com/engine/security/security/#docker-daemon-attack-surface
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No kernel memory TCP limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
WARNING: No cpu shares support```

**Comment by chadlwilson** [comment]
Is this problem replicable on a more recent dind image? I'm not familiar with the background and forum posts, but haven't experienced this before and this image is two years old, on an old/EOL Alpine version.

Is it possible that that is due to compatibility issues between Docker version on your host and inside the image?

The GoCD images just extend the docker:dind image and I don't believe there is any particular magic/customisation going on in the extensions to the image.

**Comment by gregoryfischer** [comment]
@chadlwilson as I understand it, the server and agent docker image version need to be in sync and upgrading the server at this time is not feasible.

**Comment by chadlwilson** [comment]
They don't need to fully be kept in sync as agents do bootstrap their code from the server. Generally it's wise to keep them roughly in sync though as the Java version requirements do change over time. It's also wise to upgrade the server for security reasons. Having said this, usually a newer agent image is more likely to be compatible with an older server than the other way around though. You could try it, at least to confirm whether the issue is specific to old agent dind images.

In any case, it seems unlikely to be able to get much specirfc help with a 2 year old version unless you've also confirmed the same problem exists on more recent versions.

Other than that, if your sudo commands are supposed.to be done inside the container (rather than the host) and  fix the problem, you can build a custom image from GoCD"s one with your own Dockerfile and then do anything you like in the image build between `USER` commands e.g

```
FROM gocd/go-agent-docker-dind:v19.12.0
USER root
RUN stuff
USER go
```

**Comment by gregoryfischer** [comment]
Using a v20 or v21 agent version with v19x server is incompatible due to following error.

`[stderr] - Running GoCD requires Java version >= VERSION_11 and <= 13. You are currently running with Java version 15. GoCD will now exit!`

**Comment by chadlwilson** [comment]
Ok. Can't remember the specific version where the Java version was upgraded to 14, but you could dig to find the maximum version that will work given that check.

Other than that, I suppose you might need to build your own custom image one way or another (to either fix the problem or replicate it with newer image content).
